from __future__ import annotations

from pathlib import Path

from docx import Document as WordDocument
from docx.enum.text import WD_BREAK
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Pt

from lao_document_ocr.models import Block, BlockType, Document

DEFAULT_FONT = "Noto Sans Lao"
DEFAULT_LANGUAGE = "lo-LA"


def _set_run_language(run, language: str = DEFAULT_LANGUAGE) -> None:
    run_properties = run._element.get_or_add_rPr()
    lang = run_properties.find(qn("w:lang"))
    if lang is None:
        lang = OxmlElement("w:lang")
        run_properties.append(lang)
    lang.set(qn("w:val"), language)
    lang.set(qn("w:eastAsia"), language)
    lang.set(qn("w:bidi"), language)


def _set_run_font(run, font_name: str) -> None:
    run.font.name = font_name
    run_properties = run._element.get_or_add_rPr()
    fonts = run_properties.find(qn("w:rFonts"))
    if fonts is None:
        fonts = OxmlElement("w:rFonts")
        run_properties.insert(0, fonts)
    for attribute in ("ascii", "hAnsi", "eastAsia", "cs"):
        fonts.set(qn(f"w:{attribute}"), font_name)


def _add_text(paragraph, text: str, font_name: str, bold: bool = False) -> None:
    parts = text.splitlines() or [text]
    for index, part in enumerate(parts):
        run = paragraph.add_run(part)
        run.bold = bold
        _set_run_font(run, font_name)
        _set_run_language(run)
        if index < len(parts) - 1:
            run.add_break(WD_BREAK.LINE)


def _add_block(word: WordDocument, block: Block, font_name: str) -> None:
    if block.type == BlockType.HEADING:
        paragraph = word.add_heading(level=max(1, min(9, block.level or 1)))
        _add_text(paragraph, block.text, font_name, bold=True)
        return

    if block.type == BlockType.LIST:
        for line in block.text.splitlines():
            paragraph = word.add_paragraph(style="List Bullet")
            _add_text(paragraph, line, font_name)
        return

    if block.type == BlockType.TABLE and block.cells:
        max_row = max(cell.row for cell in block.cells) + 1
        max_column = max(cell.column for cell in block.cells) + 1
        table = word.add_table(rows=max_row, cols=max_column)
        table.style = "Table Grid"
        for cell in block.cells:
            target = table.cell(cell.row, cell.column)
            target.text = ""
            _add_text(target.paragraphs[0], cell.text, font_name)
        return

    paragraph = word.add_paragraph()
    _add_text(paragraph, block.text, font_name)


def export_docx(
    document: Document,
    path: str | Path,
    *,
    font_name: str = DEFAULT_FONT,
) -> Path:
    destination = Path(path)
    word = WordDocument()

    normal_style = word.styles["Normal"]
    normal_style.font.name = font_name
    normal_style.font.size = Pt(11)

    for page_index, page in enumerate(document.pages):
        for block in page.blocks:
            _add_block(word, block, font_name)
        if page_index < len(document.pages) - 1:
            word.add_page_break()

    core = word.core_properties
    core.title = document.source_name or "OCR document"
    core.subject = "Generated by Lao Document OCR"

    word.save(destination)
    return destination
